name: login
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Thin.ttf
    - family: Poppins-bold
      fonts:
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
  assets:
    - lib/assets/login-sit.png

  uses-material-design: true


